<?php 
    $tag00 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
    $tag01 = "<mets:mets xmlns:rights=\"http://www.loc.gov/rights/\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" xmlns:oai_dc=\"http://www.openarchives.org/OAI/2.0/oai_dc/\" xmlns:mets=\"http://www.loc.gov/METS/\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://www.loc.gov/METS/ http://www.loc.gov/standards/mets/mets.xsd http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd\">\n";
    $tag02 = "<metsHdr CREATEDATE=\"{{current_timestamp}}\" LASTMODDATE=\"{{current_timestamp}}\" RECORDSTATUS=\"Production\">\n";
    $tag03 = "<mets:agent ROLE=\"CREATOR\" TYPE=\"REPOSITORY\">\n";
    $tag04 = "<mets:name>University of Kentucky</mets:name>\n";
    $tag05 = "<mets:note>SIP METS submitted to KDL.</mets:note>\n";
    $tag06 = "</mets:agent>\n";
    $tag07 = "<mets:agent ROLE=\"PRESERVATION\" TYPE=\"ORGANIZATION\">\n";
    $tag08 = "<mets:name>University of Kentucky</mets:name>\n";
    $tag09 = "<mets:note>SIP METS and associated file(s) submitted in University of Kentucky Preservation Repository.</mets:note>\n";
    $tag10 = "</mets:agent>\n";
    $tag11 = "</metsHdr>\n";
    $tag12 = "<mets:dmdSec ID=\"DMD1\">\n";
    $tag13 = "<mets:mdWrap MIMETYPE=\"text/xml\" MDTYPE=\"OAI_DC\">\n";
    $tag14 = "<mets:xmlData>\n";
    $tag15 = "<oai_dc:dc \n";
    $tag16 = "    xmlns:oai_dc=\"http://www.openarchives.org/OAI/2.0/oai_dc/\" \n";
    $tag17 = "    xmlns:dc=\"http://purl.org/dc/elements/1.1/\" \n";
    $tag18 = "    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" \n";
    $tag19 = "    xsi:schemaLocation=\"http://www.openarchives.org/OAI/2.0/oai_dc/\n";
    $tag20 = "    http://www.openarchives.org/OAI/2.0/oai_dc.xsd\">\n";
    $tag21 = "  <dc:title xml:lang=\"en\">";
    $tag22 = "</dc:title>\n";
    $tag23 = "  <dc:creator>";
    $tag24 = "</dc:creator>\n";
    $tag25 = "  <dc:publisher>";
    $tag26 = "</dc:publisher>\n";
    $tag27 = "  <dc:date>";
    $tag28 = "</dc:date>\n";
    $tag29 = "  <dc:source>";
    $tag30 = "</dc:source>\n";
    $tag31 = "  <dc:format>";
    $tag32 = "</dc:format>\n";
    $tag33 = " <dc:type>";
    $tag34 = "</dc:type>\n";
    $tag35 = "  <dc:coverage>";
    $tag36 = "</dc:coverage>\n";
    $tag37 = "  <dc:identifier>";
    $tag38 = "</dc:identifier>\n";
    $tag39 = "  <dc:language>";
    $tag40 = "</dc:language>\n";
    $tag41 = "  <dc:rights xml:lang=\"en\">";
    $tag42 = "</dc:rights>\n";
    $tag43 = "</oai_dc:dc>\n";
    $tag44 = "</mets:xmlData>\n";
    $tag45 = "</mets:mdWrap>\n";
    $tag46 = "</mets:dmdSec>\n";
    $tag47 = "<mets:amdSec>\n";
    $tag48 = "  <mets:rightsMD ID=\"RMD1\">\n";
    $tag49 = "    <mets:mdWrap MDTYPE=\"OTHER\" MIMETYPE=\"text/xml\" OTHERMDTYPE=\"RIGHTSMD\">\n";
    $tag50 = "      <mets:xmlData>\n";
    $tag51 = "        <mets:versionStatement>{{current_year}}</mets:versionStatement>\n";
    $tag52 = "      </mets:xmlData>\n";
    $tag53 = "    </mets:mdWrap>\n";
    $tag54 = "  </mets:rightsMD>\n";
    $tag55 = "<mets:rightsMD ID=\"ADMRTS1\">\n";
    $tag56 = "<mets:mdWrap MDTYPE=\"OTHER\" OTHERMDTYPE=\"METSRights\">\n";
    $tag57 = "<mets:xmlData>\n";
    $tag58 = "<mets:RightsDeclarationMD RIGHTSCATEGORY=\"\">\n";
    $tag59 = "<mets:Context CONTEXTCLASS=\"GENERAL PUBLIC\">\n";
    $tag60 = "<mets:Constraints CONSTRAINTTYPE=\"RE-USE\">\n";
    $tag61 = "<mets:ConstraintDescription>Contact repository to obtain rights information.</mets:ConstraintDescription>\n";
    $tag62 = "</mets:Constraints>\n";
    $tag63 = "</mets:Context>\n";
    $tag64 = "</mets:RightsDeclarationMD>\n";
    $tag65 = "</mets:xmlData>\n";
    $tag66 = "</mets:mdWrap>\n";
    $tag67 = "</mets:rightsMD>\n";
    $tag68 = "</mets:amdSec>\n";
    $tag69 = "{{{pagination}}}\n";
    $tag70 = "</mets:mets>\n";
?>
