<?php 
    $tag00 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
    $tag01 = "<mets:mets xmlns:rights=\"http://www.loc.gov/rights/\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" xmlns:oai_dc=\"http://www.openarchives.org/OAI/2.0/oai_dc/\" xmlns:mets=\"http://www.loc.gov/METS/\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://www.loc.gov/METS/ http://www.loc.gov/standards/mets/mets.xsd http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd\">\n";
    $tag02 = "<metsHdr CREATEDATE=\"{{current_timestamp}}\" LASTMODDATE=\"{{current_timestamp}}\" RECORDSTATUS=\"Production\">\n";
    $tag03 = "<mets:agent ROLE=\"CREATOR\" TYPE=\"REPOSITORY\">\n";
    $tag04 = "<mets:name>University of Kentucky</mets:name>\n";
    $tag05 = "<mets:note>SIP METS submitted to KDL.</mets:note>\n";
    $tag06 = "</mets:agent>\n";
    $tag07 = "<mets:agent ROLE=\"PRESERVATION\" TYPE=\"ORGANIZATION\">\n";
    $tag08 = "<mets:name>University of Kentucky</mets:name>\n";
    $tag09 = "<mets:note>SIP METS and associated file(s) submitted in University of Kentucky Preservation Repository.</mets:note>\n";
    $tag10 = "</mets:agent>\n";
    $tag11 = "</metsHdr>\n";
    $tag12 = "<mets:dmdSec ID=\"DMD1\">\n";
    $tag13 = "<mets:mdWrap MIMETYPE=\"text/xml\" MDTYPE=\"OAI_DC\">\n";
    $tag14 = "<mets:xmlData>\n";
    $tag15 = "<oai_dc:dc \n";
    $tag16 = "    xmlns:oai_dc=\"http://www.openarchives.org/OAI/2.0/oai_dc/\" \n";
    $tag17 = "    xmlns:dc=\"http://purl.org/dc/elements/1.1/\" \n";
    $tag18 = "    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" \n";
    $tag19 = "    xsi:schemaLocation=\"http://www.openarchives.org/OAI/2.0/oai_dc/\n";
    $tag20 = "    http://www.openarchives.org/OAI/2.0/oai_dc.xsd\">\n";
    $tag21 = "  <dc:title xml:lang=\"en\">";
    $tag22 = "</dc:title>\n";
    $tag23 = "  <dc:creator>";
    $tag24 = "</dc:creator>\n";
    $tag25 = "  <dc:publisher>";
    $tag26 = "</dc:publisher>\n";
    $tag27 = "  <dc:date>";
    $tag28 = "</dc:date>\n";
    $tag29 = "  <dc:source>";
    $tag30 = "</dc:source>\n";
    $tag31 = "  <dc:format>";
    $tag32 = "</dc:format>\n";
    $tag33 = " <dc:type>image</dc:type>\n";
    $tag34 = "  <dc:coverage>";
    $tag35 = "</dc:coverage>\n";
    $tag36 = "  <dc:identifier>";
    $tag37 = "</dc:identifier>\n";
    $tag38 = "  <dc:language>English</dc:language>\n";
    $tag39 = "  <dc:rights xml:lang=\"en\">This digital resource may be freely searched and displayed.  Permission must be received for subsequent distribution in print or electronically.  Physical rights are retained by the owning repository.  Copyright is retained in accordance with U. S. copyright laws.  Please go to https://exploreuk.uky.edu for more information.</dc:rights>\n";
    $tag40 = "</oai_dc:dc>\n";
    $tag41 = "</mets:xmlData>\n";
    $tag42 = "</mets:mdWrap>\n";
    $tag43 = "</mets:dmdSec>\n";
    $tag44 = "<mets:amdSec>\n";
    $tag45 = "  <mets:rightsMD ID=\"RMD1\">\n";
    $tag46 = "    <mets:mdWrap MDTYPE=\"OTHER\" MIMETYPE=\"text/xml\" OTHERMDTYPE=\"RIGHTSMD\">\n";
    $tag47 = "      <mets:xmlData>\n";
    $tag48 = "        <mets:versionStatement>{{current_year}}</mets:versionStatement>\n";
    $tag49 = "      </mets:xmlData>\n";
    $tag50 = "    </mets:mdWrap>\n";
    $tag51 = "  </mets:rightsMD>\n";
    $tag52 = "<mets:rightsMD ID=\"ADMRTS1\">\n";
    $tag53 = "<mets:mdWrap MDTYPE=\"OTHER\" OTHERMDTYPE=\"METSRights\">\n";
    $tag54 = "<mets:xmlData>\n";
    $tag55 = "<mets:RightsDeclarationMD RIGHTSCATEGORY=\"\">\n";
    $tag56 = "<mets:Context CONTEXTCLASS=\"GENERAL PUBLIC\">\n";
    $tag57 = "<mets:Constraints CONSTRAINTTYPE=\"RE-USE\">\n";
    $tag58 = "<mets:ConstraintDescription>Contact repository to obtain rights information.</mets:ConstraintDescription>\n";
    $tag59 = "</mets:Constraints>\n";
    $tag60 = "</mets:Context>\n";
    $tag61 = "</mets:RightsDeclarationMD>\n";
    $tag62 = "</mets:xmlData>\n";
    $tag63 = "</mets:mdWrap>\n";
    $tag64 = "</mets:rightsMD>\n";
    $tag65 = "</mets:amdSec>\n";
    $tag66 = "{{{pagination}}}\n";
    $tag67 = "</mets:mets>\n";
?>
